In [1]:
import pandas as pd
#Fruit   Date    Name    Number

ds = [{'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 7},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 8},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Mike',  'number': 9},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Steve', 'number': 10},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Bob',   'number': 1},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Bob',   'number': 2},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Tom',   'number': 15},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Mike',  'number': 57},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Bob',   'number': 65},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Tony',  'number': 1},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 1},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tom',   'number': 87},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 22},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 12},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tony',  'number': 15}]


ds = [{'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 7, 'value': 5.00},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 8, 'value': 5.00},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Mike',  'number': 9, 'value': 10.00},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Steve', 'number': 10, 'value': 1.00},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Bob',   'number': 1, 'value': 1.00},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Bob',   'number': 2, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Tom',   'number': 15, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Mike',  'number': 57, 'value': 5.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Bob',   'number': 65, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Tony',  'number': 1, 'value': 5.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 1, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tom',   'number': 87, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 22, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 12, 'value': 2.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tony',  'number': 15, 'value': 2.00}]


# index=range(0,4), columns=['A']
# Selectijng columns
#  columns=['fruit','name','number']
# df2 = pd.DataFrame(ds, columns=['fruit','name','number'])

newcols = {
    'fruit':'A', 
    'name':'B', 
    'number':'C'
}
# creating data frame
df2 = pd.DataFrame(ds, columns=newcols)

df2 = pd.DataFrame(ds, columns=newcols).sort_values(['fruit','name'])
df2g = df2.groupby(['fruit','name'] ).sum()


print ('--------')
print (df2)
print ('--------')
for a in df2:
    print ('single..:', a) 
    
#for b in df2g:
#    print ('df2g..:', b)
    
print df2.groupby(['fruit','name'] ).sum()    
#for b in df2g['number']:
#    print ('df2g number..:', b)
    
print (df2g['number'][0])
print (df2g['number'][1])
#print df2g['A']


#print df2g['fruit']

# You can do a loop
print ('for loop....')
#print  ('{0} {1} {2}'.format(df2g['fruit'][1], df2g['name'][1], df2g['number'][1]))
print df2g.columns
#print  (df2g['number'][0],df2g['number'][1])

# Converting to dict / Json
print "df2 to dict"
print df2.to_dict()


print "df2g to dict grouping"
print df2g.to_dict()


print "Group bu name..:"
print df2.groupby(['fruit','name'] ).sum() 
print "iterating dictionary"


# print loop
d_items = df2.to_dict()
d_item = df2.to_dict()

#print d_items['fruit'][0], d_items['name'][0], d_items['number'][0]


print dir(d_item)
print(len(d_item))
print(d_item.items())
print(d_item.values())
print(len(df2))


#for x, d_item in enumerate(d_items):

print ('First Grouping....') 
# {'fruit': {0: 'Apples', 1: 'Apples', 2: 'Apples', 3: 'Apples', 4: 'Apples', 5: 'Oranges', 6: 'Oranges', 7: 'Oranges', 8: 'Oranges', 9: 'Oranges', 10: 'Grapes', 11: 'Grapes', 12: 'Grapes', 13: 'Grapes', 14: 'Grapes'}, 'name': {0: 'Bob', 1: 'Bob', 2: 'Mike', 3: 'Steve', 4: 'Bob', 5: 'Bob', 6: 'Tom', 7: 'Mike', 8: 'Bob', 9: 'Tony', 10: 'Bob', 11: 'Tom', 12: 'Bob', 13: 'Bob', 14: 'Tony'}, 'number': {0: 7, 1: 8, 2: 9, 3: 10, 4: 1, 5: 2, 6: 15, 7: 57, 8: 65, 9: 1, 10: 1, 11: 87, 12: 22, 13: 12, 14: 15}}
for i in range(len(df2)):
    #print ('range number...:', i) 
    print '{0:>15}  {1:>10}   {2:>10}'.format(d_item['fruit'][i], d_item['name'][i], d_item['number'][i])
# printtotal
print 'summing first group..:', df2.sum()['number']  # Sum for all items 

""" Idle
print ('First Grouping Ordered....') 
from collections import OrderedDict
unordered_dict = df2.set_index('Unique_id').T.to_dict('list')
d_item_orded = OrderedDict((k,unordered_dict.get(k)) for k in df.Unique_id)

print ('ordered...:', d_item_orded)
#d_item_orded = df2.to_dict()

# {'fruit': {0: 'Apples', 1: 'Apples', 2: 'Apples', 3: 'Apples', 4: 'Apples', 5: 'Oranges', 6: 'Oranges', 7: 'Oranges', 8: 'Oranges', 9: 'Oranges', 10: 'Grapes', 11: 'Grapes', 12: 'Grapes', 13: 'Grapes', 14: 'Grapes'}, 'name': {0: 'Bob', 1: 'Bob', 2: 'Mike', 3: 'Steve', 4: 'Bob', 5: 'Bob', 6: 'Tom', 7: 'Mike', 8: 'Bob', 9: 'Tony', 10: 'Bob', 11: 'Tom', 12: 'Bob', 13: 'Bob', 14: 'Tony'}, 'number': {0: 7, 1: 8, 2: 9, 3: 10, 4: 1, 5: 2, 6: 15, 7: 57, 8: 65, 9: 1, 10: 1, 11: 87, 12: 22, 13: 12, 14: 15}}
for i in range(len(df2)):
    #print ('range number...:', i) 
    print '{0:>15}  {1:>10}   {2:>10}'.format(d_item['fruit'][i], d_item['name'][i], d_item['number'][i])
# printtotal
print 'summing first orded..:', df2.sum()['number']  # Sum for all items 
"""


print ('Second Grouping - List by grouping....') 
# {'number': {('Grapes', 'Tom'): 87, ('Grapes', 'Tony'): 15, ('Grapes', 'Bob'): 35, ('Apples', 'Mike'): 9, ('Oranges', 'Tony'): 1, ('Oranges', 'Bob'): 67, ('Apples', 'Steve'): 10, ('Apples', 'Bob'): 16, ('Oranges', 'Mike'): 57, ('Oranges', 'Tom'): 15}}
d_items_g = df2g.to_dict()
for  idx, val in d_items_g['number'].items():
    #print ("show index  and value")
    print '{0:>15}  {1:>10}   {2:>10}'.format(idx[0], idx[1], val)

#for i in range(len(df2g)):
#print ('range number...:', i) 

# getting total by groups
print '{0:>15}  '.format(d_items_g['number'][('Grapes', 'Bob')])

print ('First & Second Grouping - more then one total field....') 


print ('Three Grouping - more one total field....')

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(df2)? (<ipython-input-1-3766abbceaf5>, line 56)

In [ ]:
import pandas as pd
#Fruit   Date    Name    Number




ds = [{'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 7, 'value': 5.00},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 8, 'value': 5.00},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Mike',  'number': 9, 'value': 10.00},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Steve', 'number': 10, 'value': 1.00},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Bob',   'number': 1, 'value': 1.00},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Bob',   'number': 2, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Tom',   'number': 15, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Mike',  'number': 57, 'value': 5.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Bob',   'number': 65, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Tony',  'number': 1, 'value': 5.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 1, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tom',   'number': 87, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 22, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 12, 'value': 2.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tony',  'number': 15, 'value': 2.00}]


# index=range(0,4), columns=['A']
# Selectijng columns
#  columns=['fruit','name','number']
# df2 = pd.DataFrame(ds, columns=['fruit','name','number'])
newcols = {
    'fruit':'A', 
    'name':'B', 
    'number':'C',
    'value':'D'
}

df2 = pd.DataFrame(ds, columns=newcols)

df2 = pd.DataFrame(ds, columns=newcols).sort_values(['fruit','name'])
df2g = df2.groupby(['fruit','name'] ).sum()
# This changes dictionary representation
#df2g = df2.groupby(['fruit','name'],as_index = False).sum().pivot('fruit','name').fillna(0)


# print loop
d_item = df2.to_dict()
print 'df2g new group settings'
print df2g


print ('First - listing....') 
# {'fruit': {0: 'Apples', 1: 'Apples', 2: 'Apples', 3: 'Apples', 4: 'Apples', 5: 'Oranges', 6: 'Oranges', 7: 'Oranges', 8: 'Oranges', 9: 'Oranges', 10: 'Grapes', 11: 'Grapes', 12: 'Grapes', 13: 'Grapes', 14: 'Grapes'}, 'name': {0: 'Bob', 1: 'Bob', 2: 'Mike', 3: 'Steve', 4: 'Bob', 5: 'Bob', 6: 'Tom', 7: 'Mike', 8: 'Bob', 9: 'Tony', 10: 'Bob', 11: 'Tom', 12: 'Bob', 13: 'Bob', 14: 'Tony'}, 'number': {0: 7, 1: 8, 2: 9, 3: 10, 4: 1, 5: 2, 6: 15, 7: 57, 8: 65, 9: 1, 10: 1, 11: 87, 12: 22, 13: 12, 14: 15}}
for i in range(len(df2)):
    #print ('range number...:', i) 
    print '{0:>15}  {1:>10}   {2:>10}   {3:>10}'.format(d_item['fruit'][i], d_item['name'][i], d_item['number'][i], d_item['value'][i])
# printtotal
print 'summing first group..:', df2.sum()['number'], df2.sum()['value']  # Sum for all items 

# Strategy: I got both of the separately:: Use them one after the other!!!!

print 'just sum ...:'
print df2.sum()

# Representation has been changed
d_items_g = df2g.to_dict()
print 'd_items_g..:', d_items_g

print ('Second Grouping - List by grouping....') 
# {'number': {('Grapes', 'Tom'): 87, ('Grapes', 'Tony'): 15, ('Grapes', 'Bob'): 35, ('Apples', 'Mike'): 9, ('Oranges', 'Tony'): 1, ('Oranges', 'Bob'): 67, ('Apples', 'Steve'): 10, ('Apples', 'Bob'): 16, ('Oranges', 'Mike'): 57, ('Oranges', 'Tom'): 15}}

for  idx, val in d_items_g['number'].items():
    #print ("show index  and value")
    print '{0:>15}  {1:>10}   {2:>10}'.format(idx[0], idx[1], val)

#for i in range(len(df2g)):
#print ('range number...:', i) 

# getting total by groups
print 'Number..: {0:>15}  '.format(d_items_g['number'][('Grapes', 'Bob')])
print 'Value...: {0:>15}  '.format(d_items_g['value'][('Grapes', 'Bob')])
for  idx in range(len(df2g)):
     print ('idx..:', idx)
     #print  d_items_g['number']
     #print ("show index  and value")
     #print '{0:>15}  {1:>10}   {2:>10}'.format(idx[0], idx[1], val)

    
# sort strategy - Tentar aplicar um sort; e um set para remover os itens repetidos
print  d_items_g['number']
print  d_items_g['value']

    
print "content  grouping ...:"
print (d_items_g)

In [ ]:
import pandas as pd
#Fruit   Date    Name    Number




ds = [{'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 7, 'value': 5.00},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Bob',   'number': 8, 'value': 5.00},
 {'fruit': 'Apples',  'data': '10/6/2016', 'name': 'Mike',  'number': 9, 'value': 10.00},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Steve', 'number': 10, 'value': 1.00},
 {'fruit': 'Apples',  'data': '10/7/2016', 'name': 'Bob',   'number': 1, 'value': 1.00},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Bob',   'number': 2, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Tom',   'number': 15, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Mike',  'number': 57, 'value': 5.00},
 {'fruit': 'Oranges', 'data': '10/6/2016', 'name': 'Bob',   'number': 65, 'value': 2.00},
 {'fruit': 'Oranges', 'data': '10/7/2016', 'name': 'Tony',  'number': 1, 'value': 5.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 1, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tom',   'number': 87, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 22, 'value': 1.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Bob',   'number': 12, 'value': 2.00},
 {'fruit': 'Grapes',  'data': '10/7/2016', 'name': 'Tony',  'number': 15, 'value': 2.00}]


# index=range(0,4), columns=['A']
# Selectijng columns
#  columns=['fruit','name','number']
# df2 = pd.DataFrame(ds, columns=['fruit','name','number'])
newcols = {
    'fruit':'A', 
    'name':'B', 
    'number':'C',
    'value':'D'
}

df2 = pd.DataFrame(ds, columns=newcols)

df2 = pd.DataFrame(ds, columns=newcols).sort_values(['fruit','name'])
df2g = df2.groupby(['fruit','name'] ).sum()
# This changes dictionary representation
df2g = df2.groupby(['fruit','name'],as_index = False).sum().pivot('fruit','name').fillna(0)


# print loop
d_item = df2.to_dict()
print 'df2g new group settings'
print df2g


print ('First - listing....') 
# {'fruit': {0: 'Apples', 1: 'Apples', 2: 'Apples', 3: 'Apples', 4: 'Apples', 5: 'Oranges', 6: 'Oranges', 7: 'Oranges', 8: 'Oranges', 9: 'Oranges', 10: 'Grapes', 11: 'Grapes', 12: 'Grapes', 13: 'Grapes', 14: 'Grapes'}, 'name': {0: 'Bob', 1: 'Bob', 2: 'Mike', 3: 'Steve', 4: 'Bob', 5: 'Bob', 6: 'Tom', 7: 'Mike', 8: 'Bob', 9: 'Tony', 10: 'Bob', 11: 'Tom', 12: 'Bob', 13: 'Bob', 14: 'Tony'}, 'number': {0: 7, 1: 8, 2: 9, 3: 10, 4: 1, 5: 2, 6: 15, 7: 57, 8: 65, 9: 1, 10: 1, 11: 87, 12: 22, 13: 12, 14: 15}}
for i in range(len(df2)):
    #print ('range number...:', i) 
    print '{0:>15}  {1:>10}   {2:>10}   {3:>10}'.format(d_item['fruit'][i], d_item['name'][i], d_item['number'][i], d_item['value'][i])
# printtotal
print 'summing first group..:', df2.sum()['number'], df2.sum()['value']  # Sum for all items 

# Strategy: I got both of the separately:: Use them one after the other!!!!

print 'just sum ...:'
print df2.sum()

# Representation has been changed
d_items_g = df2g.to_dict()
print 'd_items_g..:', d_items_g

print ('Second Grouping - List by grouping....') 
# {'number': {('Grapes', 'Tom'): 87, ('Grapes', 'Tony'): 15, ('Grapes', 'Bob'): 35, ('Apples', 'Mike'): 9, ('Oranges', 'Tony'): 1, ('Oranges', 'Bob'): 67, ('Apples', 'Steve'): 10, ('Apples', 'Bob'): 16, ('Oranges', 'Mike'): 57, ('Oranges', 'Tom'): 15}}

for  idx, val in d_items_g['number'].items():
    #print ("show index  and value")
    print '{0:>15}  {1:>10}   {2:>10}'.format(idx[0], idx[1], val)

#for i in range(len(df2g)):
#print ('range number...:', i) 

# getting total by groups
print 'Number..: {0:>15}  '.format(d_items_g['number'][('Grapes', 'Bob')])
print 'Value...: {0:>15}  '.format(d_items_g['value'][('Grapes', 'Bob')])
for  idx in range(len(df2g)):
     print ('idx..:', idx)
     #print  d_items_g['number']
     #print ("show index  and value")
     #print '{0:>15}  {1:>10}   {2:>10}'.format(idx[0], idx[1], val)

    
# sort strategy - Tentar aplicar um sort; e um set para remover os itens repetidos
print  d_items_g['number']
print  d_items_g['value']

    
print "content  grouping ...:"
print (d_items_g)

In [ ]:
# How do I get totalizations  # Visoes separadas

d_items_g..: {('number', 'Tom'): {'Oranges': 15.0, 'Apples': 0.0, 'Grapes': 87.0}, 
              ('number', 'Mike'): {'Oranges': 57.0, 'Apples': 9.0, 'Grapes': 0.0}, 
              ('value', 'Steve'): {'Oranges': 0.0, 'Apples': 1.0, 'Grapes': 0.0},
              ('number', 'Tony'): {'Oranges': 1.0, 'Apples': 0.0, 'Grapes': 15.0},
              ('number', 'Bob'): {'Oranges': 67.0, 'Apples': 16.0, 'Grapes': 35.0}, 
              ('value', 'Tony'): {'Oranges': 5.0, 'Apples': 0.0, 'Grapes': 2.0}, 
              ('number', 'Steve'): {'Oranges': 0.0, 'Apples': 10.0, 'Grapes': 0.0},
              ('value', 'Bob'): {'Oranges': 4.0, 'Apples': 11.0, 'Grapes': 4.0},
              ('value', 'Mike'): {'Oranges': 5.0, 'Apples': 10.0, 'Grapes': 0.0},
              ('value', 'Tom'): {'Oranges': 2.0, 'Apples': 0.0, 'Grapes': 1.0}}

{'number': {('Grapes', 'Tom'): 87, ('Grapes', 'Tony'): 15, ('Grapes', 'Bob'): 35, 
            ('Apples', 'Mike'): 9, ('Oranges', 'Tony'): 1, ('Oranges', 'Bob'): 67,
            ('Apples', 'Steve'): 10, ('Apples', 'Bob'): 16, ('Oranges', 'Mike'): 57, 
            ('Oranges', 'Tom'): 15}, 
 'value': {('Grapes', 'Tom'): 1.0, ('Grapes', 'Tony'): 2.0, ('Grapes', 'Bob'): 4.0, 
           ('Apples', 'Mike'): 10.0, ('Oranges', 'Tony'): 5.0, ('Oranges', 'Bob'): 4.0, 
           ('Apples', 'Steve'): 1.0, ('Apples', 'Bob'): 11.0, ('Oranges', 'Mike'): 5.0, 
           ('Oranges', 'Tom'): 2.0}}